# Generated by Django 5.2.12 on 2026-03-12 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_alter_claim_zd_ticket_id'),
        ('communications', '0002_alter_emaillog_action_required_alter_emaillog_claim_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='alias_matched',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Matched alias if any', max_length=255),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='auto_resolved',
            field=models.BooleanField(db_index=True, default=False, help_text='Auto-resolved by AI'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='category',
            field=models.CharField(choices=[('OBJECT_FOUND', 'Object Found'), ('OBJECT_NOT_FOUND', 'Object Not Found'), ('RESUBMISSION_REQUIRED', 'Resubmission Required'), ('SUBMISSION_CONFIRMATION', 'Submission Confirmation'), ('GENERAL_CORRESPONDENCE', 'General Correspondence'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=30),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='delivered_to',
            field=models.EmailField(blank=True, db_index=True, default='', help_text='Actual delivery address (for alias matching)', max_length=254),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='from_email',
            field=models.EmailField(db_index=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='raw_headers',
            field=models.TextField(blank=True, default='', help_text='Full email headers'),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='to_email',
            field=models.EmailField(blank=True, db_index=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='emaillog',
            name='zd_ticket_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='claims.claim'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['category', 'auto_resolved'], name='communicati_categor_775b3b_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['from_email', '-received_at'], name='communicati_from_em_ed9436_idx'),
        ),
    ]
