# Generated by Django 5.2.12 on 2026-03-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_prompt_template', models.TextField(default='You are an assistant for the Lost Object Recovery Automation (LORA) system.\nYour task is to analyze lost object claims and help determine the appropriate action.\n\nClaim Details:\n- Item: {item_description}\n- Location: {location}\n- Date Lost: {date_lost}\n- Claimant: {claimant_name}\n- Status: {status}\n\nPlease analyze this claim and provide:\n1. Recommended action (approve, reject, needs_review)\n2. Confidence level (high, medium, low)\n3. Reasoning for your recommendation\n4. Any additional information needed', help_text='Template for AI analysis of claims. Use {variable} placeholders.')),
                ('imap_host', models.CharField(default='imap.gmail.com', help_text='IMAP server hostname', max_length=255)),
                ('imap_user', models.CharField(help_text='IMAP username/email', max_length=255)),
                ('imap_pass', models.CharField(help_text='IMAP password or app-specific password', max_length=255)),
                ('zd_subdomain', models.CharField(help_text='Zendesk subdomain (e.g., "company" in company.zendesk.com)', max_length=100)),
                ('zd_token', models.CharField(help_text='Zendesk API token', max_length=255)),
                ('zd_email', models.CharField(help_text='Zendesk account email', max_length=255)),
                ('paypal_client_id', models.CharField(help_text='PayPal API Client ID', max_length=255)),
                ('paypal_secret', models.CharField(help_text='PayPal API Secret', max_length=255)),
                ('paypal_webhook_id', models.CharField(help_text='PayPal Webhook ID for event notifications', max_length=255)),
                ('sidebar_secret_token', models.CharField(help_text='Secret token for Zendesk sidebar authentication', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
    ]
