# Generated by Django 5.2.12 on 2026-03-12 01:51

import apps.config.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_systemsettings_dispute_response_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='imap_pass',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='IMAP password or app-specific password (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='paypal_client_id',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='PayPal API Client ID (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='paypal_secret',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='PayPal API Secret (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='sidebar_secret_token',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='Secret token for Zendesk sidebar authentication (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='zd_agent_password',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, help_text='Zendesk agent password for browser authentication (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='zd_token',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='Zendesk API token (encrypted at rest)', max_length=4580),
        ),
    ]
