# Generated by Django 5.2.11 on 2026-03-17 14:44

import apps.config.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0005_alter_systemsettings_imap_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='ai_api_base',
            field=models.CharField(default='https://api.deepseek.com/v1', help_text='AI API base URL (e.g., https://api.deepseek.com/v1)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_api_key',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='AI API key (encrypted at rest)', max_length=4580),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_api_model',
            field=models.CharField(default='deepseek-chat', help_text='AI model name (e.g., deepseek-chat, qwen-plus)', max_length=100),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='ai_provider',
            field=models.CharField(default='DeepSeek', help_text='AI provider name (e.g., DeepSeek, Qwen)', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='imap_pass',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='IMAP password or app-specific password (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='paypal_client_id',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='PayPal API Client ID (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='paypal_secret',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='PayPal API Secret (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='sidebar_secret_token',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='Secret token for Zendesk sidebar authentication (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='zd_agent_password',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, help_text='Zendesk agent password for browser authentication (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='zd_token',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='Zendesk API token (encrypted at rest)', max_length=4580),
        ),
    ]
