# Generated by Django 5.2.12 on 2026-03-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='PayPal event ID (e.g., WH-EVENT-XXXXX)', max_length=100, unique=True)),
                ('event_type', models.CharField(help_text='PayPal event type (e.g., CUSTOMER.DISPUTE.CREATED)', max_length=100)),
                ('resource_type', models.CharField(blank=True, help_text='Resource type (e.g., dispute)', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='Resource ID from PayPal', max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the event was processed')),
                ('status', models.CharField(default='processed', help_text='Processing status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
            ],
            options={
                'verbose_name': 'Processed Webhook Event',
                'verbose_name_plural': 'Processed Webhook Events',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['-processed_at'], name='payments_pr_process_66d1af_idx'), models.Index(fields=['event_type', '-processed_at'], name='payments_pr_event_t_cbb240_idx')],
            },
        ),
    ]
