# Generated by Django 5.2.14 on 2026-06-22 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0025_claim_zd_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormFill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_url', models.URLField(max_length=1000)),
                ('browser_use_session_id', models.CharField(blank=True, default='', max_length=128)),
                ('browser_use_workspace_id', models.CharField(blank=True, default='', max_length=128)),
                ('status', models.CharField(choices=[('STARTED', 'Started'), ('FILLED', 'Filled — awaiting approval'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='STARTED', max_length=12)),
                ('image_source', models.CharField(choices=[('none', 'No image'), ('ticket', 'From ticket attachment'), ('upload', 'Agent uploaded')], default='none', max_length=8)),
                ('image_name', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='form_fill_images/')),
                ('confirmation_screenshot', models.FileField(blank=True, null=True, upload_to='form_fill_screenshots/')),
                ('result_output', models.TextField(blank=True, default='')),
                ('error', models.TextField(blank=True, default='')),
                ('posted_to_ticket', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filled_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fills', to='claims.claim')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['claim', '-created_at'], name='integration_claim_i_c55f1a_idx')],
            },
        ),
    ]
