# Generated by Django 5.2.14 on 2026-06-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfill',
            name='post_screenshot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='formfill',
            name='status',
            field=models.CharField(choices=[('STARTED', 'Started'), ('FILLED', 'Filled — awaiting approval'), ('SUBMITTING', 'Submitting'), ('SUBMITTED', 'Submitted'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed')], default='STARTED', max_length=12),
        ),
    ]
