# Generated by Django 5.2.14 on 2026-06-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_formfill_post_screenshot_alter_formfill_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPlaybook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Form host, e.g. chargerback.com (lowercased)', max_length=255, unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('instructions', models.TextField(blank=True, default='', help_text="Site-specific how-to injected into the agent's brief")),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['domain'],
            },
        ),
    ]
