# Generated by Django 5.2.12 on 2026-03-12 00:48

import apps.config.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0002_alter_systemsettings_imap_pass_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='dispute_response_prompt',
            field=models.TextField(default="You are drafting a professional response letter for a PayPal dispute.\n\nDispute Information:\n- Reason: {dispute_reason}\n- Amount: {dispute_amount} {dispute_currency}\n- Buyer: {buyer_name} ({buyer_email})\n- Transaction: {transaction_id} on {transaction_date}\n\nZendesk Ticket Information:\n- Ticket ID: {zd_ticket_id}\n- Subject: {ticket_subject}\n- Status: {ticket_status}\n\nBased on the Zendesk ticket data and communication history, draft a professional response letter that:\n1. Acknowledges the customer's concern\n2. Presents the facts from the ticket history\n3. Explains any resolution actions taken\n4. Maintains a courteous and professional tone\n\nResponse Letter:", help_text='Template for AI-generated dispute response letters'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_analysis_prompt',
            field=models.TextField(default='You are analyzing an incoming email for a lost object recovery service.\n\nEmail Content:\n- Subject: {subject}\n- Body: {body}\n\nAnalyze this email and provide:\n1. Summary: Brief summary of the email content\n2. Sentiment: Positive, Neutral, Frustrated, or Urgent\n3. Category: OBJECT_FOUND, OBJECT_NOT_FOUND, RESUBMISSION_REQUIRED, SUBMISSION_CONFIRMATION, GENERAL_CORRESPONDENCE, or UNKNOWN\n4. Action Required: true/false - Does this email require human agent attention?\n5. Auto Resolvable: true/false - Can this be automatically resolved without human intervention?\n\nRespond with JSON in this format:\n{\n  "summary": "...",\n  "sentiment": "...",\n  "category": "...",\n  "action_required": true/false,\n  "auto_resolvable": true/false\n}', help_text='Template for AI email categorization and analysis'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='email_domain',
            field=models.CharField(blank=True, help_text='Domain for alias matching (e.g., mydomain.com)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='zd_agent_email',
            field=models.CharField(blank=True, help_text='Zendesk agent email for browser authentication (encrypted)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='zd_agent_password',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, help_text='Zendesk agent password for browser authentication (encrypted at rest)', max_length=4580),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='zd_alias_custom_field_id',
            field=models.CharField(blank=True, help_text='Zendesk custom field ID storing the email alias', max_length=50),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='imap_pass',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='IMAP password or app-specific password (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='paypal_client_id',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='PayPal API Client ID (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='paypal_secret',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='PayPal API Secret (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='sidebar_secret_token',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='Secret token for Zendesk sidebar authentication (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='zd_token',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='Zendesk API token (encrypted at rest)', max_length=4580),
        ),
    ]
