# Generated by Django 5.2.11 on 2026-03-17 18:15

import apps.config.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0006_systemsettings_ai_api_base_systemsettings_ai_api_key_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('AI', 'AI Provider'), ('IMAP', 'IMAP Email'), ('ZENDESK', 'Zendesk'), ('PAYPAL', 'PayPal'), ('SCHEDULER', 'Email Scheduler'), ('SCREENSHOT', 'Screenshot Service')], help_text='The service this status entry represents', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('disconnected', 'Disconnected'), ('error', 'Error'), ('running', 'Running'), ('stopped', 'Stopped')], default='disconnected', help_text='Current connection/operational status', max_length=20)),
                ('is_enabled', models.BooleanField(default=True, help_text='Whether this service is enabled (toggle control)')),
                ('last_checked', models.DateTimeField(auto_now_add=True, help_text='Last time the connection was tested')),
                ('last_error', models.TextField(blank=True, default='', help_text='Last error message if status is error')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional service-specific metadata')),
            ],
            options={
                'verbose_name': 'Service Status',
                'verbose_name_plural': 'Service Statuses',
                'ordering': ['service'],
            },
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='ai_api_key',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='AI API key (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='imap_pass',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='IMAP password or app-specific password (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='paypal_client_id',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='PayPal API Client ID (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='paypal_secret',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='PayPal API Secret (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='sidebar_secret_token',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='Secret token for Zendesk sidebar authentication (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='zd_agent_password',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, help_text='Zendesk agent password for browser authentication (encrypted at rest)', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='zd_token',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='Zendesk API token (encrypted at rest)', max_length=4580),
        ),
    ]
