# Generated by Django 5.2.14 on 2026-06-10 11:03

import apps.config.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0013_systemsettings_pii_tokenization_salt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='ai_api_key',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='AI API key (encrypted at rest)', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='imap_pass',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='IMAP password or app-specific password (encrypted at rest)', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='paypal_client_id',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='PayPal API Client ID (encrypted at rest)', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='paypal_secret',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='PayPal API Secret (encrypted at rest)', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='pii_tokenization_salt',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='HMAC-SHA256 key for deterministic PII placeholder generation. If empty, falls back to the PII_TOKENIZATION_SALT env var. Set a long random value (32+ bytes hex-encoded) for production.', max_length=4580),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='sidebar_secret_token',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='Secret token for Zendesk sidebar authentication (encrypted at rest)', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='zd_agent_password',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, help_text='Zendesk agent password for browser authentication (encrypted at rest)', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='zd_token',
            field=apps.config.encrypted_fields.EncryptedCharField(help_text='Zendesk API token (encrypted at rest)', max_length=255),
        ),
    ]
