# Generated by Django 5.2.14 on 2026-06-11 17:16

import apps.config.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0014_alter_systemsettings_ai_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='aerodatabox_api_key',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='AeroDataBox (RapidAPI) key for flight lookups (encrypted at rest)', max_length=255),
        ),
    ]
