# Generated by Django 5.2.14 on 2026-06-11 18:32

import apps.config.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0015_systemsettings_aerodatabox_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='imap_pass',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='IMAP password or app-specific password (encrypted at rest)', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='imap_user',
            field=models.CharField(blank=True, default='', help_text='IMAP username/email', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='paypal_client_id',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='PayPal API Client ID (encrypted at rest)', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='paypal_secret',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='PayPal API Secret (encrypted at rest)', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='paypal_webhook_id',
            field=models.CharField(blank=True, default='', help_text='PayPal Webhook ID for event notifications', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='sidebar_secret_token',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='Secret token for Zendesk sidebar authentication (encrypted at rest)', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='zd_email',
            field=models.CharField(blank=True, default='', help_text='Zendesk account email', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='zd_subdomain',
            field=models.CharField(blank=True, default='', help_text='Zendesk subdomain (e.g., "company" in company.zendesk.com)', max_length=100),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='zd_token',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='Zendesk API token (encrypted at rest)', max_length=255),
        ),
    ]
