# Generated by Django 5.2.14 on 2026-06-11 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0016_alter_systemsettings_imap_pass_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='email_analysis_prompt',
            field=models.TextField(default='You are analyzing an incoming email for a lost object recovery service.\n\nEmail Content:\n- Subject: {subject}\n- Body: {body}\n\nAnalyze this email and provide:\n1. Summary: Brief summary of the email content\n2. Category: OBJECT_FOUND, OBJECT_NOT_FOUND, RESUBMISSION_REQUIRED, SUBMISSION_CONFIRMATION, GENERAL_CORRESPONDENCE, or UNKNOWN\n3. Action Required: true/false - Does this email require human agent attention?\n4. Auto Resolvable: true/false - Can this be automatically resolved without human intervention?\n\nRespond with JSON in this format:\n{\n  "summary": "...",\n  "category": "...",\n  "action_required": true/false,\n  "auto_resolvable": true/false\n}', help_text='Template for AI email categorization and analysis'),
        ),
    ]
