# Generated by Django 5.2.14 on 2026-06-12 13:46

import apps.config.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0017_alter_systemsettings_email_analysis_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='woocommerce_consumer_key',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='WooCommerce REST API consumer key (ck_…, Read/Write; encrypted at rest)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='woocommerce_consumer_secret',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='WooCommerce REST API consumer secret (cs_…; encrypted at rest)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='woocommerce_store_url',
            field=models.URLField(blank=True, default='', help_text='WooCommerce store base URL, e.g. https://store.example.com (no trailing path)'),
        ),
    ]
