# Generated by Django 5.2.14 on 2026-06-12 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0018_systemsettings_woocommerce_consumer_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestatus',
            name='service',
            field=models.CharField(choices=[('AI', 'AI Provider'), ('IMAP', 'IMAP Email'), ('ZENDESK', 'Zendesk'), ('PAYPAL', 'PayPal'), ('WOOCOMMERCE', 'WooCommerce'), ('SCHEDULER', 'Email Scheduler'), ('SCREENSHOT', 'Screenshot Service')], help_text='The service this status entry represents', max_length=20, unique=True),
        ),
    ]
