# Generated by Django 5.2.14 on 2026-06-13 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0019_alter_servicestatus_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='paypal_mode',
            field=models.CharField(choices=[('sandbox', 'Sandbox (test — no real money)'), ('live', 'Live (real money)')], default='sandbox', help_text='Which PayPal environment dispute/refund API calls hit. Defaults to SANDBOX — set to Live only when ready to move real money.', max_length=10),
        ),
    ]
