# Generated by Django 5.2.14 on 2026-06-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0020_systemsettings_paypal_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='client_report_trigger_status',
            field=models.CharField(blank=True, default='', help_text='Zendesk status name that triggers drafting the client "what we did" update (e.g. "Claim submitted"). Leave blank to disable the feature.', max_length=64),
        ),
    ]
