# Generated by Django 5.2.14 on 2026-06-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0021_systemsettings_client_report_trigger_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='client_report_trigger_status_id',
            field=models.CharField(blank=True, default='', help_text='Zendesk custom-status ID that triggers drafting the client "what we did" update + the follow-up cadence (e.g. the "Claim submitted" status ID). This is the authoritative trigger. Leave blank to disable the feature.', max_length=32),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='client_updates_autosend',
            field=models.BooleanField(default=False, help_text='When ON, the run_client_updates job auto-drafts and sends due client progress updates as public Zendesk replies. When OFF (default), updates are only scheduled for an agent to prepare and send manually.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='service_length_days',
            field=models.PositiveIntegerField(default=30, help_text='Length of the concierge service in days, measured from claim creation. Drives the client-update cadence tail and the final end-of-service email.'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='client_report_trigger_status',
            field=models.CharField(blank=True, default='', help_text='LEGACY: Zendesk status NAME that triggers the client update. Prefer the status-ID field below. Leave blank to disable name matching.', max_length=64),
        ),
    ]
