# Generated by Django 5.2.14 on 2026-06-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0022_systemsettings_client_report_trigger_status_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='email_sweep_autorun',
            field=models.BooleanField(default=False, help_text='When ON, the scheduled job sweeps the shared inbox for institution replies and auto-categorises them (acts on live tickets). When OFF (default), email is only checked per-ticket via the manual button.'),
        ),
    ]
