# Generated by Django 5.2.14 on 2026-06-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0023_systemsettings_email_sweep_autorun'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicestatus',
            name='service',
            field=models.CharField(choices=[('AI', 'AI Provider'), ('IMAP', 'IMAP Email'), ('ZENDESK', 'Zendesk'), ('PAYPAL', 'PayPal'), ('WOOCOMMERCE', 'WooCommerce'), ('SCHEDULER', 'Email Scheduler')], help_text='The service this status entry represents', max_length=20, unique=True),
        ),
    ]
