# Generated by Django 5.2.14 on 2026-06-14 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0024_alter_servicestatus_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='zd_agent_email',
        ),
        migrations.RemoveField(
            model_name='systemsettings',
            name='zd_agent_password',
        ),
    ]
