# Generated by Django 5.2.14 on 2026-06-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0025_remove_systemsettings_zd_agent_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='import_claims_from_email',
            field=models.BooleanField(default=False, help_text='When ON, an inbound institution email that matches a Zendesk ticket with no local claim imports that existing claim from Zendesk on the spot. Never creates a new claim. Requires the inbox sweep to be ON. Intended as a temporary backlog-transition helper.'),
        ),
    ]
