# Generated by Django 5.2.14 on 2026-06-16 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0027_create_cache_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemsettings',
            name='dispute_response_prompt',
        ),
    ]
