# Generated by Django 5.2.14 on 2026-06-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0028_remove_systemsettings_dispute_response_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='terms_conditions_pdf',
            field=models.FileField(blank=True, help_text='Terms & Conditions PDF, attached to PayPal dispute first responses', null=True, upload_to='settings/'),
        ),
    ]
