# Generated by Django 5.2.14 on 2026-06-20 10:12

import apps.config.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0029_systemsettings_terms_conditions_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='oblio_cif',
            field=models.CharField(blank=True, default='', help_text='Your company tax id / CIF, required by the Oblio invoice API', max_length=32),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='oblio_email',
            field=models.CharField(blank=True, default='', help_text='Oblio API client id (the account email)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='oblio_secret',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='Oblio API secret (encrypted at rest)', max_length=255),
        ),
    ]
