# Generated by Django 5.2.14 on 2026-06-20 16:40

import apps.config.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0030_systemsettings_oblio_cif_systemsettings_oblio_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='anthropic_api_base',
            field=models.CharField(default='https://api.anthropic.com', help_text='Anthropic API base URL (rarely changed)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='anthropic_api_key',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='Anthropic (Claude) API key — used only for dispute reports (encrypted at rest)', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='anthropic_model',
            field=models.CharField(choices=[('claude-sonnet-4-6', 'Claude Sonnet 4.6 (recommended for disputes)'), ('claude-opus-4-8', 'Claude Opus 4.8 (most capable)'), ('claude-haiku-4-5', 'Claude Haiku 4.5 (fastest, cheapest)')], default='claude-sonnet-4-6', help_text='Claude model used for dispute report generation', max_length=100),
        ),
    ]
