# Generated by Django 5.2.14 on 2026-06-22 10:55

import apps.config.encrypted_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0031_systemsettings_anthropic_api_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='browser_use_api_key',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='Browser Use Cloud API key (bu_...), encrypted at rest. Powers the Zendesk Form filling tab.', max_length=255),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='browser_use_model',
            field=models.CharField(blank=True, default='claude-sonnet-4.6', help_text='Model Browser Use runs the form-filling agent on.', max_length=64),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='form_filling_enabled',
            field=models.BooleanField(default=False, help_text='When ON, the Zendesk Form filling tab can drive Browser Use to fill institution forms from a claim. OFF by default.'),
        ),
    ]
