# Generated by Django 5.2.14 on 2026-06-22 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0032_systemsettings_browser_use_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='recover_orphan_emails',
            field=models.BooleanField(default=False, help_text='When ON, each scheduled run re-routes orphaned emails (already swept, no ticket match at the time) to their tickets. Idempotent — turn ON to clear the backlog, watch one run, then turn OFF.'),
        ),
    ]
