# Generated by Django 5.2.14 on 2026-06-23 00:01

import apps.config.encrypted_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0033_recover_orphan_emails_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='browser_use_webhook_secret',
            field=apps.config.encrypted_fields.EncryptedCharField(blank=True, default='', help_text='Signing code Browser Use shows when you create the webhook. LORA uses it to verify incoming task-status callbacks (HMAC-SHA256). Encrypted at rest.', max_length=255),
        ),
    ]
