# Generated by Django 5.2.12 on 2026-03-11 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('body', models.TextField()),
                ('ai_summary', models.TextField(blank=True)),
                ('sentiment', models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Frustrated', 'Frustrated'), ('Urgent', 'Urgent')], max_length=20)),
                ('action_required', models.BooleanField(default=False)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='claims.claim')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
    ]
