# Generated by Django 5.2.12 on 2026-03-12 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_alter_claim_zd_ticket_id'),
        ('communications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='action_required',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='claim',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='claims.claim'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='received_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='sentiment',
            field=models.CharField(blank=True, choices=[('Positive', 'Positive'), ('Neutral', 'Neutral'), ('Frustrated', 'Frustrated'), ('Urgent', 'Urgent')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['-received_at'], name='communicati_receive_bcd954_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['claim', '-received_at'], name='communicati_claim_i_76d14c_idx'),
        ),
        migrations.AddIndex(
            model_name='emaillog',
            index=models.Index(fields=['sentiment', 'action_required'], name='communicati_sentime_044c4e_idx'),
        ),
    ]
