# Generated by Django 5.2.11 on 2026-03-17 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_emaillog_alias_matched_emaillog_auto_resolved_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='emaillog',
            name='communicati_sentime_044c4e_idx',
        ),
        migrations.RemoveField(
            model_name='emaillog',
            name='sentiment',
        ),
    ]
