# Generated by Django 5.2.14 on 2026-06-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0004_remove_emaillog_communicati_sentime_044c4e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emaillog',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=512),
        ),
    ]
