# Generated by Django 5.2.14 on 2026-06-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0020_claim_email_alias'),
        ('communications', '0005_emaillog_message_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='emaillog',
            constraint=models.UniqueConstraint(condition=models.Q(('message_id', ''), _negated=True), fields=('message_id',), name='uniq_emaillog_message_id'),
        ),
    ]
