# Generated by Django 5.2.14 on 2026-06-14 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0021_claim_client_report_draft_and_more'),
        ('communications', '0006_emaillog_uniq_emaillog_message_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone', models.CharField(choices=[('DAY_2', 'Day 2'), ('DAY_5', 'Day 5'), ('DAY_11', 'Day 11'), ('DAY_21', 'Day 21')], max_length=10)),
                ('due_at', models.DateTimeField(db_index=True)),
                ('state', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DRAFTED', 'Drafted'), ('SENT', 'Sent'), ('SKIPPED', 'Skipped')], db_index=True, default='SCHEDULED', max_length=10)),
                ('draft_body', models.TextField(blank=True, default='')),
                ('has_news', models.BooleanField(default=False, help_text='True if the draft reflects new developments (vs a "still searching" note)')),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_up_updates', to='claims.claim')),
            ],
            options={
                'ordering': ['due_at'],
                'indexes': [models.Index(fields=['state', 'due_at'], name='communicati_state_97d557_idx')],
                'constraints': [models.UniqueConstraint(fields=('claim', 'milestone'), name='uniq_clientupdate_claim_milestone')],
            },
        ),
    ]
