# Generated by Django 5.2.14 on 2026-06-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0007_clientupdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientupdate',
            name='milestone',
            field=models.CharField(max_length=10),
        ),
    ]
