# Generated by Django 5.2.14 on 2026-06-23 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0008_alter_clientupdate_milestone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emaillog',
            name='category',
            field=models.CharField(choices=[('OBJECT_FOUND', 'Object Found'), ('OBJECT_NOT_FOUND', 'Object Not Found'), ('SHIPPING_INFORMATION', 'Shipping Information'), ('RESUBMISSION_REQUIRED', 'Resubmission Required'), ('SUBMISSION_CONFIRMATION', 'Submission Confirmation'), ('GENERAL_CORRESPONDENCE', 'General Correspondence'), ('UNKNOWN', 'Unknown')], db_index=True, default='UNKNOWN', max_length=30),
        ),
    ]
