# Generated by Django 5.2.12 on 2026-03-12 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_alter_claim_zd_ticket_id'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_dispute_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('paypal_case_id', models.CharField(blank=True, db_index=True, max_length=100)),
                ('zd_ticket_id', models.CharField(blank=True, db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('MATCHED', 'Matched to Zendesk Ticket'), ('GATHERING_DATA', 'Gathering Data'), ('DOCUMENTS_READY', 'Documents Ready'), ('UNDER_REVIEW', 'Under Review'), ('EVIDENCE_SENT', 'Evidence Sent to PayPal'), ('RESOLVED_WON', 'Resolved - Won'), ('RESOLVED_LOST', 'Resolved - Lost'), ('ACCEPTED', 'Accepted/Refunded')], db_index=True, default='RECEIVED', max_length=30)),
                ('dispute_reason', models.CharField(blank=True, choices=[('MERCHANDISE_OR_SERVICE_NOT_RECEIVED', 'Merchandise/Service Not Received'), ('MERCHANDISE_OR_SERVICE_NOT_AS_DESCRIBED', 'Merchandise/Service Not As Described'), ('UNAUTHORIZED_TRANSACTION', 'Unauthorized Transaction'), ('CREDIT_NOT_PROCESSED', 'Credit Not Processed'), ('DUPLICATE_TRANSACTION', 'Duplicate Transaction'), ('INCORRECT_AMOUNT', 'Incorrect Amount'), ('OTHER', 'Other')], max_length=50)),
                ('dispute_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('dispute_currency', models.CharField(blank=True, max_length=3)),
                ('buyer_email', models.EmailField(db_index=True, max_length=254)),
                ('buyer_name', models.CharField(blank=True, max_length=255)),
                ('transaction_id', models.CharField(db_index=True, max_length=100)),
                ('transaction_date', models.DateTimeField()),
                ('seller_response_due', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_webhook_payload', models.JSONField(default=dict)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_disputes', to=settings.AUTH_USER_MODEL)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='claims.claim')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DISPUTE_CREATED', 'Dispute Created'), ('DISPUTE_MATCHED', 'Dispute Matched to Ticket'), ('SCREENSHOTS_CAPTURED', 'Screenshots Captured'), ('DOCUMENT_GENERATED', 'Document Generated'), ('DOCUMENT_ACCEPTED', 'Document Accepted'), ('EVIDENCE_SENT', 'Evidence Sent to PayPal'), ('STATUS_CHANGED', 'Status Changed'), ('NOTE_ADDED', 'Note Added'), ('DISPUTE_RESOLVED', 'Dispute Resolved')], max_length=50)),
                ('details', models.TextField(blank=True)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='payments.dispute')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(choices=[('RESPONSE_LETTER', 'Response Letter'), ('EVIDENCE_REPORT', 'Evidence Report')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('SENT', 'Sent to PayPal')], db_index=True, default='DRAFT', max_length=20)),
                ('file_path', models.FileField(blank=True, null=True, upload_to='dispute_documents/')),
                ('content_html', models.TextField(blank=True, help_text='Inline HTML content for editing')),
                ('version', models.IntegerField(default=1)),
                ('generated_by', models.CharField(choices=[('AI', 'AI Generated'), ('MANUAL', 'Manually Created')], default='AI', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_documents', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='payments.dispute')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeScreenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dispute_screenshots/')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('page_url', models.URLField(blank=True, max_length=500)),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshots', to='payments.dispute')),
            ],
            options={
                'ordering': ['-captured_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProcessedWebhookEvent',
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['-created_at'], name='payments_di_created_058e13_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', '-created_at'], name='payments_di_status_45cb06_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['buyer_email', '-created_at'], name='payments_di_buyer_e_f7a8f5_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['transaction_id'], name='payments_di_transac_5da1cc_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeactivitylog',
            index=models.Index(fields=['dispute', '-performed_at'], name='payments_di_dispute_940110_idx'),
        ),
        migrations.AddIndex(
            model_name='disputedocument',
            index=models.Index(fields=['dispute', '-created_at'], name='payments_di_dispute_564fce_idx'),
        ),
        migrations.AddIndex(
            model_name='disputedocument',
            index=models.Index(fields=['doc_type', 'status'], name='payments_di_doc_typ_0f5730_idx'),
        ),
        migrations.AddIndex(
            model_name='disputescreenshot',
            index=models.Index(fields=['dispute', '-captured_at'], name='payments_di_dispute_9cf8be_idx'),
        ),
    ]
