# Generated by Django 5.2.12 on 2026-03-12 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_alter_claim_client_email'),
        ('payments', '0002_dispute_disputeactivitylog_disputedocument_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='claims.claim'),
        ),
        migrations.CreateModel(
            name='ProcessedWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, help_text='PayPal event ID (e.g., WH-EVENT-XXXXX)', max_length=100, unique=True)),
                ('event_type', models.CharField(help_text='PayPal event type (e.g., CUSTOMER.DISPUTE.CREATED)', max_length=100)),
                ('resource_type', models.CharField(blank=True, help_text='Resource type (e.g., dispute)', max_length=100)),
                ('resource_id', models.CharField(blank=True, help_text='Resource ID from PayPal', max_length=100)),
                ('processed_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the event was processed')),
                ('status', models.CharField(choices=[('processed', 'Processed'), ('failed', 'Failed')], default='processed', help_text='Processing status', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed')),
            ],
            options={
                'verbose_name': 'Processed Webhook Event',
                'verbose_name_plural': 'Processed Webhook Events',
                'ordering': ['-processed_at'],
                'indexes': [models.Index(fields=['-processed_at'], name='payments_pr_process_66d1af_idx'), models.Index(fields=['event_type', '-processed_at'], name='payments_pr_event_t_cbb240_idx')],
            },
        ),
    ]
