# Generated by Django 5.2.11 on 2026-03-17 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_alter_claim_client_email_alter_claim_created_at_and_more'),
        ('payments', '0003_alter_dispute_claim_processedwebhookevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['claim', '-created_at'], name='payments_di_claim_i_278901_idx'),
        ),
        migrations.AddIndex(
            model_name='disputedocument',
            index=models.Index(fields=['accepted_by', '-created_at'], name='payments_di_accepte_ec4c92_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.CheckConstraint(check=~(models.Q(claim__isnull=False) & models.Q(buyer_email='')), name='dispute_claim_requires_buyer_email'),
        ),
    ]
