# Generated by Django 5.2.11 on 2026-03-17 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_alter_claim_status'),
        ('payments', '0004_dispute_payments_di_claim_i_278901_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paypal_refund_id', models.CharField(db_index=True, help_text='PayPal refund transaction ID', max_length=100, unique=True)),
                ('paypal_capture_id', models.CharField(blank=True, help_text='Original PayPal capture ID', max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount', max_digits=10)),
                ('currency', models.CharField(default='USD', help_text='Currency code (e.g., USD, EUR)', max_length=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', help_text='Current refund status', max_length=20)),
                ('refund_type', models.CharField(choices=[('FULL', 'Full Refund'), ('PARTIAL', 'Partial Refund')], help_text='Full or Partial refund', max_length=10)),
                ('external_source', models.CharField(choices=[('LORA', 'LORA Initiated'), ('WOOCOMMERCE', 'WooCommerce/WordPress'), ('MANUAL', 'Manual Entry')], default='LORA', help_text='Origin of the refund', max_length=20)),
                ('reason', models.TextField(help_text='Reason for the refund')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='PayPal API response and additional data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, help_text='When the refund was processed/completed', null=True)),
                ('claim', models.ForeignKey(blank=True, help_text='Claim associated with this refund', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='claims.claim')),
                ('created_by', models.ForeignKey(help_text='User who initiated the refund', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['claim', 'status'], name='payments_re_claim_i_a284b8_idx'), models.Index(fields=['paypal_refund_id'], name='payments_re_paypal__25c36f_idx'), models.Index(fields=['external_source', 'created_at'], name='payments_re_externa_2a19e3_idx')],
            },
        ),
    ]
