# Generated by Django 5.2.11 on 2026-03-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_refund'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refund',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='REQUESTED', help_text='Current refund status', max_length=20),
        ),
    ]
