# Generated by Django 5.2.14 on 2026-06-10 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0016_alter_claimevidence_description'),
        ('payments', '0006_alter_refund_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dispute',
            name='dispute_claim_requires_buyer_email',
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.CheckConstraint(condition=models.Q(('buyer_email', ''), ('claim__isnull', False), _negated=True), name='dispute_claim_requires_buyer_email'),
        ),
    ]
