# Generated by Django 5.2.14 on 2026-06-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_remove_dispute_dispute_claim_requires_buyer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='dispute_life_cycle_stage',
            field=models.CharField(blank=True, default='', help_text='PayPal dispute_life_cycle_stage; gates evidence submission', max_length=30),
        ),
    ]
