# Generated by Django 5.2.14 on 2026-06-13 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_dispute_dispute_life_cycle_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispute',
            name='dispute_reason',
            field=models.CharField(blank=True, choices=[('MERCHANDISE_OR_SERVICE_NOT_RECEIVED', 'Item/Service Not Received'), ('MERCHANDISE_OR_SERVICE_NOT_AS_DESCRIBED', 'Not As Described'), ('UNAUTHORISED', 'Unauthorised Transaction'), ('CREDIT_NOT_PROCESSED', 'Credit Not Processed'), ('DUPLICATE_TRANSACTION', 'Duplicate Transaction'), ('INCORRECT_AMOUNT', 'Incorrect Amount'), ('PAYMENT_BY_OTHER_MEANS', 'Paid By Other Means'), ('CANCELED_RECURRING_BILLING', 'Cancelled Recurring Billing'), ('PROBLEM_WITH_REMITTANCE', 'Problem With Remittance'), ('OTHER', 'Other')], max_length=50),
        ),
    ]
