# Generated by Django 5.2.14 on 2026-06-14 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_remap_unauthorised_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DisputeScreenshot',
        ),
    ]
