# Generated by Django 5.2.14 on 2026-06-14 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_delete_disputescreenshot'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dispute',
            name='dispute_claim_requires_buyer_email',
        ),
    ]
