# Generated by Django 5.2.14 on 2026-06-14 20:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_remove_dispute_dispute_claim_requires_buyer_email'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('EVIDENCE', 'First evidence'), ('SUPPORTING_INFO', 'Supporting info'), ('MESSAGE', 'Message to buyer')], default='EVIDENCE', max_length=20)),
                ('source', models.CharField(choices=[('AI', 'AI-drafted'), ('AI_EDITED', 'AI-drafted, edited'), ('MANUAL', 'Manually written')], default='AI', max_length=10)),
                ('notes', models.TextField(blank=True, help_text='The narrative text submitted to PayPal (editable while DRAFT)')),
                ('manager_note', models.TextField(blank=True, default='', help_text='Extra context the manager typed; feeds the AI narrative, not sent verbatim')),
                ('evidence_type', models.CharField(blank=True, default='', help_text='PayPal evidence_type (provide-evidence only); defaulted per dispute reason', max_length=64)),
                ('attach_evidence_pdf', models.BooleanField(default=False, help_text='Whether to attach the latest evidence-report PDF to this submission')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=10)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('paypal_response', models.JSONField(blank=True, default=dict, help_text='Raw PayPal response (or error detail) for audit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='payments.dispute')),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeSubmissionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='dispute_submission_images/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='payments.disputesubmission')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_submission_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='disputesubmission',
            index=models.Index(fields=['dispute', '-created_at'], name='payments_di_dispute_5b069c_idx'),
        ),
        migrations.AddIndex(
            model_name='disputesubmission',
            index=models.Index(fields=['status', '-created_at'], name='payments_di_status_433f5c_idx'),
        ),
    ]
