# Generated by Django 5.2.14 on 2026-06-16 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_disputesubmission_disputesubmissionimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='accept_in_flight',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='disputesubmission',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTING', 'Submitting'), ('SUBMITTED', 'Submitted'), ('FAILED', 'Failed')], db_index=True, default='DRAFT', max_length=10),
        ),
    ]
