# Generated by Django 5.2.14 on 2026-06-16 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0015_rename_accept_in_flight_outbound_in_flight'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='outbound_in_flight_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
