# Generated by Django 5.2.14 on 2026-06-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0016_dispute_outbound_in_flight_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputesubmission',
            name='attach_terms',
            field=models.BooleanField(default=True, help_text='Attach the stored Terms & Conditions PDF (always-required on a first response)'),
        ),
    ]
