# Generated by Django 5.2.14 on 2026-06-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_disputesubmission_attach_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='disputesubmission',
            name='attach_invoice',
            field=models.BooleanField(default=True, help_text='Attach the customer invoice fetched from the order (always-required on a first response)'),
        ),
    ]
