# Generated by Django 5.2.12 on 2026-03-11 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Claim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=254, unique=True)),
                ('status', models.CharField(choices=[('Received', 'Received'), ('Searching', 'Searching'), ('Found', 'Found'), ('Shipped', 'Shipped'), ('Disputed', 'Disputed')], default='Received', max_length=20)),
                ('zd_ticket_id', models.CharField(blank=True, max_length=50)),
                ('flight_details', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClaimEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='evidence/')),
                ('description', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='claims.claim')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
