# Generated by Django 5.2.12 on 2026-03-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='client_email',
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Searching', 'Searching'), ('Found', 'Found'), ('Shipped', 'Shipped'), ('Disputed', 'Disputed')], db_index=True, default='Received', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='zd_ticket_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['-created_at'], name='claims_clai_created_015674_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status', '-created_at'], name='claims_clai_status_eafd60_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['client_email'], name='claims_clai_client__235cdf_idx'),
        ),
    ]
