# Generated by Django 5.2.12 on 2026-03-12 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_alter_claim_zd_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='client_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
