# Generated by Django 5.2.11 on 2026-03-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0007_alter_claim_client_email_alter_claim_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Searching', 'Searching'), ('Found', 'Found'), ('Shipped', 'Shipped'), ('Disputed', 'Disputed'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='Received', max_length=20),
        ),
    ]
