# Generated by Django 5.2.11 on 2026-03-17 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0008_alter_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Searching', 'Searching'), ('Found', 'Found'), ('Shipped', 'Shipped'), ('Disputed', 'Disputed'), ('REFUND_REQUESTED', 'Refund Requested'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='Received', max_length=20),
        ),
    ]
