# Generated by Django 5.2.11 on 2026-03-17 22:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0009_alter_claim_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='alf_claim_id',
            field=models.CharField(blank=True, db_index=True, help_text='ALF claim ID (format: ALF1234567) from Zendesk ticket subject', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='alternate_email',
            field=models.EmailField(blank=True, help_text='Alternate contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='claim',
            name='llm_extraction_failed',
            field=models.BooleanField(default=False, help_text='True if LLM failed to extract data from Zendesk ticket'),
        ),
        migrations.AddField(
            model_name='claim',
            name='object_description',
            field=models.TextField(blank=True, help_text='Description of lost item'),
        ),
        migrations.AddField(
            model_name='claim',
            name='phone',
            field=models.CharField(blank=True, help_text='Client phone number', max_length=50),
        ),
        migrations.AlterField(
            model_name='claim',
            name='client_email',
            field=models.EmailField(db_index=True, help_text='Client email address (extracted from Zendesk ticket)', max_length=254),
        ),
        migrations.AlterField(
            model_name='claim',
            name='flight_details',
            field=models.TextField(blank=True, help_text='Flight information (number, date, route)'),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Searching', 'Searching'), ('Found', 'Found'), ('Shipped', 'Shipped'), ('Disputed', 'Disputed'), ('REFUND_REQUESTED', 'Refund Requested'), ('REFUNDED', 'Refunded'), ('PARTIALLY_REFUNDED', 'Partially Refunded')], default='Received', help_text='Current claim status', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='zd_ticket_id',
            field=models.CharField(blank=True, db_index=True, help_text='Zendesk ticket ID', max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['alf_claim_id'], name='claims_clai_alf_cla_48691c_idx'),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['zd_ticket_id'], name='claims_clai_zd_tick_d654a7_idx'),
        ),
    ]
