# Generated by Django 5.2.11 on 2026-03-17 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0010_claim_alf_claim_id_claim_alternate_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated summary from Zendesk ticket analysis (generated once at creation)'),
        ),
        migrations.CreateModel(
            name='ClaimUpdateTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zendesk_ticket_id', models.CharField(db_index=True, help_text='Zendesk ticket ID', max_length=50)),
                ('update_type', models.CharField(choices=[('STATUS_CHANGE', 'Status Change'), ('NEW_COMMENT', 'New Comment'), ('INFO_UPDATED', 'Information Updated'), ('LLM_ANALYSIS', 'LLM Analysis')], help_text='Type of update', max_length=20)),
                ('changes_summary', models.TextField(blank=True, help_text='JSON summary of what changed')),
                ('llm_summary', models.TextField(blank=True, help_text='LLM-generated summary of changes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(help_text='Claim this update belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='claims.claim')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['claim', '-created_at'], name='claims_clai_claim_i_aec95f_idx'), models.Index(fields=['zendesk_ticket_id'], name='claims_clai_zendesk_e45aca_idx')],
            },
        ),
    ]
