# Generated by Django 5.2.11 on 2026-03-18 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0011_claim_ai_summary_claimupdatetimeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='phone',
            field=models.CharField(blank=True, help_text='Client phone number', max_length=50, null=True),
        ),
    ]
