# Generated by Django 5.2.14 on 2026-06-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0012_alter_claim_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='zd_ticket_id',
            field=models.CharField(blank=True, db_index=True, help_text='Zendesk ticket ID', max_length=50, null=True, unique=True),
        ),
    ]
