# Generated by Django 5.2.14 on 2026-06-10 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0013_alter_claim_zd_ticket_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='client_name',
            field=models.CharField(blank=True, default='', help_text='Client full name (from Zendesk "Customer Name" field)', max_length=255),
        ),
    ]
