# Generated by Django 5.2.14 on 2026-06-10 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0014_claim_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='billing_address',
            field=models.TextField(blank=True, default='', help_text='Billing address (from Zendesk "Billing Address" field)'),
        ),
        migrations.AddField(
            model_name='claim',
            name='deadline_date',
            field=models.DateField(blank=True, help_text='Claim deadline date (Zendesk "Deadline Date")', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='deadline_time',
            field=models.CharField(blank=True, default='', help_text='Claim deadline time-of-day (Zendesk "Deadline Time")', max_length=20),
        ),
        migrations.AddField(
            model_name='claim',
            name='deadline_timezone',
            field=models.CharField(blank=True, default='', help_text='Timezone for the deadline (Zendesk "Deadline Time Zone")', max_length=64),
        ),
        migrations.AddField(
            model_name='claim',
            name='incident_details',
            field=models.TextField(blank=True, default='', help_text='How/when the item was lost (Zendesk "Incident Details")'),
        ),
        migrations.AddField(
            model_name='claim',
            name='lost_location',
            field=models.TextField(blank=True, default='', help_text='Where the item was lost (Zendesk "Lost Location") — primary search lead'),
        ),
        migrations.AddField(
            model_name='claim',
            name='payment_method',
            field=models.CharField(blank=True, default='', help_text='Payment method (Zendesk "Payment Method")', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='payment_status',
            field=models.CharField(blank=True, default='', help_text='Payment status from the storefront (Zendesk "Payment Status")', max_length=100),
        ),
        migrations.AddField(
            model_name='claim',
            name='price_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Concierge fee the client paid (Zendesk "Price Paid")', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='shipping_address',
            field=models.TextField(blank=True, default='', help_text='Where to ship the recovered object (Zendesk "Shipping Address")'),
        ),
        migrations.AddField(
            model_name='claim',
            name='tracking_info',
            field=models.TextField(blank=True, default='', help_text='Return-shipment tracking (Zendesk "3rd Party Tracking Information")'),
        ),
        migrations.AddField(
            model_name='claim',
            name='woocommerce_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='WooCommerce order ID (Zendesk "WooCommerce ID")', max_length=50),
        ),
    ]
