# Generated by Django 5.2.14 on 2026-06-10 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0015_claim_billing_address_claim_deadline_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimevidence',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Agent description of the evidence image'),
        ),
    ]
