# Generated by Django 5.2.14 on 2026-06-11 10:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0016_alter_claimevidence_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='ai_summary_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the AI summary was last regenerated', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='deadline_at',
            field=models.DateTimeField(blank=True, help_text='Computed deadline moment (date + best-effort time/timezone); urgency math uses this', null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='status_category',
            field=models.CharField(blank=True, choices=[('new', 'New'), ('open', 'Open'), ('pending', 'Pending'), ('hold', 'On hold'), ('solved', 'Solved')], default='open', help_text="Zendesk status family — drives grouping/colors; '' when unknown", max_length=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='status_changed_at',
            field=models.DateTimeField(blank=True, help_text='When the current status was set (from the Zendesk webhook)', null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(default='Investigation initiated', help_text='Zendesk custom status name (agent view), mirrored verbatim from the ticket', max_length=64),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['status_category', '-created_at'], name='claims_clai_status__5f148e_idx'),
        ),
    ]
