# Generated by Django 5.2.14 on 2026-06-11 12:08

from django.db import migrations


def remap_statuses(apps, schema_editor):
    from apps.claims.legacy_status_map import map_legacy_status
    from apps.claims.services import compute_deadline_at

    Claim = apps.get_model('claims', 'Claim')
    for claim in Claim.objects.all().iterator():
        name, family = map_legacy_status(claim.status)
        claim.status = name
        claim.status_category = family
        claim.status_changed_at = claim.updated_at
        claim.deadline_at = compute_deadline_at(
            claim.deadline_date, claim.deadline_time, claim.deadline_timezone)
        claim.save(update_fields=[
            'status', 'status_category', 'status_changed_at', 'deadline_at'])


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0017_claim_ai_summary_updated_at_claim_deadline_at_and_more'),
    ]

    operations = [
        migrations.RunPython(remap_statuses, migrations.RunPython.noop),
    ]
