# Generated by Django 5.2.14 on 2026-06-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0018_remap_legacy_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='flight_data',
            field=models.JSONField(blank=True, default=dict, help_text='Normalized flight lookup result; written only by the flight-lookup endpoint'),
        ),
        migrations.AddField(
            model_name='claim',
            name='flight_data_updated_at',
            field=models.DateTimeField(blank=True, help_text='When flight_data was last fetched', null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='ai_summary',
            field=models.TextField(blank=True, help_text='AI-generated case summary (regenerated at creation, on Zendesk status changes, and on manual refresh)'),
        ),
    ]
