# Generated by Django 5.2.14 on 2026-06-11 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0019_claim_flight_data_claim_flight_data_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='email_alias',
            field=models.EmailField(blank=True, default='', help_text='Per-ticket inbound email alias (Zendesk "Email Alias" field); cached here on first email check', max_length=254),
        ),
    ]
