# Generated by Django 5.2.14 on 2026-06-14 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0020_claim_email_alias'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='client_report_draft',
            field=models.TextField(blank=True, default='', help_text='Drafted client update message awaiting agent review/send'),
        ),
        migrations.AddField(
            model_name='claim',
            name='client_report_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the client update was sent as a public Zendesk reply (None = not sent)', null=True),
        ),
    ]
