# Generated by Django 5.2.14 on 2026-06-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0021_claim_client_report_draft_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='paypal_transaction_id',
            field=models.CharField(blank=True, db_index=True, default='', help_text='PayPal transaction ID (from Zendesk). Cross-checks dispute matching: a dispute links to this claim only if its PayPal transaction ID agrees with this one.', max_length=100),
        ),
    ]
