# Generated by Django 5.2.14 on 2026-06-17 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0022_claim_paypal_transaction_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='risk_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='risk_acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_claim_risks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='claim',
            name='risk_detail',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='claim',
            name='risk_first_flagged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='risk_last_signal_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='risk_level',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('watch', 'Watch'), ('at_risk', 'At risk')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='claim',
            name='risk_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
