# Generated by Django 5.2.14 on 2026-06-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0023_claim_risk_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='client_report_skipped_at',
            field=models.DateTimeField(blank=True, help_text='When an agent skipped the initial update (e.g. the claim reached LORA late and the client was already updated). None = not skipped.', null=True),
        ),
    ]
