# Generated by Django 5.2.14 on 2026-06-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0024_claim_client_report_skipped_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='zd_tags',
            field=models.JSONField(blank=True, default=list, help_text="The Zendesk ticket's tags as of the last 'Refresh from Zendesk'. Used to show client-update milestones done via the manual macros (client_update_N tags) without a live API call per page render."),
        ),
    ]
