# Generated by Django 5.2.14 on 2026-06-23 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0025_claim_zd_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='form_profile',
            field=models.JSONField(blank=True, default=dict, help_text='Clean structured form-fill profile (real values); written by the form-fill flow'),
        ),
        migrations.AddField(
            model_name='claim',
            name='form_profile_generated_at',
            field=models.DateTimeField(blank=True, help_text='When form_profile was last built', null=True),
        ),
    ]
