# Generated by Django 5.2.14 on 2026-06-24 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0026_claim_form_profile_claim_form_profile_generated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='submitted_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
