# Generated by Django 5.2.12 on 2026-03-12 00:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_client_email_alter_claim_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='Agent assigned to this claim', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='claim',
            index=models.Index(fields=['assigned_to', '-created_at'], name='claims_clai_assigne_41530c_idx'),
        ),
    ]
