# Generated by Django 5.2.12 on 2026-03-12 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0003_claim_assigned_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='zd_ticket_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
