# Generated by Django 5.2.12 on 2026-03-12 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_alter_claim_zd_ticket_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='zd_ticket_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
    ]
