# Generated by Django 5.2.12 on 2026-03-12 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_alter_claim_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='client_email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='claim',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Received', 'Received'), ('Searching', 'Searching'), ('Found', 'Found'), ('Shipped', 'Shipped'), ('Disputed', 'Disputed')], default='Received', max_length=20),
        ),
        migrations.AlterField(
            model_name='claim',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
